name: Deploy AKS

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: az
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Deploy Bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
        template: ./env/aks.bicep
        parameters: >
          clusterAdminUserName=${{ secrets.AKS_ADMIN_USERNAME }}
          sshPublicKey="${{ secrets.AKS_ADMIN_PUBLIC_KEY }}"
        deploymentName: 'deploy-${{ github.run_id }}'
        failOnStdErr: false
        additionalArguments: '--verbose'
